import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '../src/components/Button';
import { usePainInsights, useExerciseCorrelation } from '../src/hooks/useTracking';
import { useAssignments, useMe } from '../src/hooks/usePatient';
import { colors, radius, spacing, typography } from '../src/theme/tokens';

export default function ProgressReportScreen() {
  const router = useRouter();
  const me = useMe();
  const insights = usePainInsights(30);
  const corr = useExerciseCorrelation(30);
  const assignments = useAssignments();
  const [generating, setGenerating] = useState(false);

  const onGenerate = async () => {
    setGenerating(true);
    try {
      let printModule: any;
      let shareModule: any;
      try {
        printModule = require('expo-print');
        shareModule = require('expo-sharing');
      } catch {
        Alert.alert(
          'Not available',
          'PDF generation requires a dev-client build. It does not work in Expo Go.',
        );
        setGenerating(false);
        return;
      }

      const d = insights.data;
      const c = corr.data;
      const name = me.data ? `${me.data.first_name} ${me.data.last_name}` : 'Patient';
      const active = (assignments.data ?? []).filter((a) => a.status === 'active').length;
      const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

      const html = `
        <html><head><style>
          body { font-family: -apple-system, sans-serif; padding: 40px; color: #0F172A; }
          h1 { color: #1B3A5C; font-size: 24px; margin-bottom: 4px; }
          h2 { color: #1B3A5C; font-size: 18px; margin-top: 28px; border-bottom: 1px solid #E5E7EB; padding-bottom: 6px; }
          .meta { color: #4B5563; font-size: 13px; margin-bottom: 20px; }
          .stat-row { display: flex; gap: 16px; margin: 12px 0; }
          .stat { flex: 1; background: #F3F4F6; border-radius: 8px; padding: 12px; text-align: center; }
          .stat-value { font-size: 28px; font-weight: 700; }
          .stat-label { font-size: 11px; color: #4B5563; margin-top: 2px; }
          .green { color: #059669; } .red { color: #DC2626; }
          table { width: 100%; border-collapse: collapse; margin: 8px 0; }
          td, th { text-align: left; padding: 6px 8px; border-bottom: 1px solid #E5E7EB; font-size: 13px; }
          th { font-weight: 600; color: #4B5563; font-size: 11px; text-transform: uppercase; }
          .footer { margin-top: 40px; font-size: 11px; color: #9CA3AF; text-align: center; }
        </style></head><body>
          <h1>TMJConnect Progress Report</h1>
          <p class="meta">${name} \u2014 ${date} \u2014 Last 30 days</p>

          <h2>Pain Summary</h2>
          <div class="stat-row">
            <div class="stat"><div class="stat-value">${d?.overall.avg_pain ?? '—'}</div><div class="stat-label">Avg Pain / 10</div></div>
            <div class="stat"><div class="stat-value">${d?.overall.total_logs ?? 0}</div><div class="stat-label">Total Logs</div></div>
            <div class="stat"><div class="stat-value ${(d?.overall.trend ?? 0) < 0 ? 'green' : 'red'}">${(d?.overall.trend ?? 0) > 0 ? '+' : ''}${d?.overall.trend ?? 0}</div><div class="stat-label">Trend</div></div>
          </div>

          ${d?.trigger_frequency.length ? `
          <h2>Top Triggers</h2>
          <table><tr><th>Trigger</th><th>Occurrences</th></tr>
            ${d.trigger_frequency.slice(0, 5).map((t) => `<tr><td>${t.trigger}</td><td>${t.count}</td></tr>`).join('')}
          </table>` : ''}

          <h2>Exercise Impact</h2>
          ${c && c.exercise_days_count > 0 ? `
          <div class="stat-row">
            <div class="stat"><div class="stat-value green">${c.exercise_days_avg_pain}</div><div class="stat-label">Exercise days (${c.exercise_days_count}d)</div></div>
            <div class="stat"><div class="stat-value red">${c.no_exercise_days_avg_pain}</div><div class="stat-label">Rest days (${c.no_exercise_days_count}d)</div></div>
          </div>` : '<p>Not enough exercise data yet.</p>'}

          <h2>Active Exercises</h2>
          <p>${active} active assignment${active === 1 ? '' : 's'}</p>

          <div class="footer">Generated by TMJConnect \u2014 For discussion with your healthcare provider</div>
        </body></html>
      `;

      const { uri } = await printModule.printToFileAsync({ html, base64: false });
      await shareModule.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf' });
    } catch (err) {
      Alert.alert('Error', 'Could not generate report. Make sure expo-print and expo-sharing are installed.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} hitSlop={10}>
          <Ionicons name="chevron-back" size={24} color={colors.ink.primary} />
        </Pressable>
        <Text style={styles.title}>Progress Report</Text>
        <View style={{ width: 24 }} />
      </View>

      <View style={styles.content}>
        <View style={styles.iconCircle}>
          <Ionicons name="document-text" size={40} color={colors.navy.standard} />
        </View>
        <Text style={styles.heading}>Share your progress</Text>
        <Text style={styles.body}>
          Generate a PDF summary of your last 30 days — pain trends, triggers, exercise impact — to share with your provider at your next appointment.
        </Text>

        <View style={styles.includes}>
          <IncludeRow label="30-day pain summary + trend" />
          <IncludeRow label="Top triggers breakdown" />
          <IncludeRow label="Exercise compliance impact" />
          <IncludeRow label="Active assignments count" />
        </View>

        <Button title="Generate PDF" onPress={onGenerate} loading={generating} />
      </View>
    </SafeAreaView>
  );
}

function IncludeRow({ label }: { label: string }) {
  return (
    <View style={styles.includeRow}>
      <Ionicons name="checkmark-circle" size={18} color={colors.success.base} />
      <Text style={styles.includeText}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: spacing.lg, paddingVertical: spacing.md,
    borderBottomWidth: 1, borderBottomColor: colors.surface.border,
  },
  title: { ...typography.h2, color: colors.ink.primary },
  content: { flex: 1, padding: spacing.xl, alignItems: 'center', justifyContent: 'center' },
  iconCircle: {
    width: 80, height: 80, borderRadius: 40,
    backgroundColor: colors.navy.ghost, alignItems: 'center', justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  heading: { ...typography.h2, color: colors.ink.primary, marginBottom: spacing.sm },
  body: { ...typography.body, color: colors.ink.secondary, textAlign: 'center', marginBottom: spacing.xl },
  includes: { width: '100%', marginBottom: spacing.xl, gap: spacing.sm },
  includeRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  includeText: { ...typography.body, color: colors.ink.primary },
});
