import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { ChevronRight, MoreHorizontal } from 'lucide-react';
import { cn } from '@/lib/utils';
export const Breadcrumb = React.forwardRef(({ ...props }, ref) => _jsx("nav", { ref: ref, "aria-label": "breadcrumb", ...props }));
Breadcrumb.displayName = 'Breadcrumb';
export const BreadcrumbList = React.forwardRef(({ className, ...props }, ref) => (_jsx("ol", { ref: ref, className: cn('flex flex-wrap items-center gap-1.5 break-words font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground', className), ...props })));
BreadcrumbList.displayName = 'BreadcrumbList';
export const BreadcrumbItem = React.forwardRef(({ className, ...props }, ref) => (_jsx("li", { ref: ref, className: cn('inline-flex items-center gap-1.5', className), ...props })));
BreadcrumbItem.displayName = 'BreadcrumbItem';
export const BreadcrumbLink = React.forwardRef(({ asChild, className, ...props }, ref) => {
    const Comp = asChild ? Slot : 'a';
    return (_jsx(Comp, { ref: ref, className: cn('transition-colors hover:text-foreground', className), ...props }));
});
BreadcrumbLink.displayName = 'BreadcrumbLink';
export const BreadcrumbPage = React.forwardRef(({ className, ...props }, ref) => (_jsx("span", { ref: ref, role: "link", "aria-disabled": "true", "aria-current": "page", className: cn('text-foreground', className), ...props })));
BreadcrumbPage.displayName = 'BreadcrumbPage';
export const BreadcrumbSeparator = ({ children, className, ...props }) => (_jsx("li", { role: "presentation", "aria-hidden": "true", className: cn('opacity-50', className), ...props, children: children ?? _jsx(ChevronRight, { className: "h-3 w-3" }) }));
BreadcrumbSeparator.displayName = 'BreadcrumbSeparator';
export const BreadcrumbEllipsis = ({ className, ...props }) => (_jsxs("span", { role: "presentation", "aria-hidden": "true", className: cn('flex h-4 w-4 items-center justify-center', className), ...props, children: [_jsx(MoreHorizontal, { className: "h-3 w-3" }), _jsx("span", { className: "sr-only", children: "More" })] }));
BreadcrumbEllipsis.displayName = 'BreadcrumbEllipsis';
